// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: srv.proto

package flutter_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_srv_proto_rawDescGZIP(), []int{0}
}

type TextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextReply) Reset() {
	*x = TextReply{}
	mi := &file_srv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReply) ProtoMessage() {}

func (x *TextReply) ProtoReflect() protoreflect.Message {
	mi := &file_srv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReply.ProtoReflect.Descriptor instead.
func (*TextReply) Descriptor() ([]byte, []int) {
	return file_srv_proto_rawDescGZIP(), []int{1}
}

func (x *TextReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TextsAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []*Text                `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextsAnswer) Reset() {
	*x = TextsAnswer{}
	mi := &file_srv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextsAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextsAnswer) ProtoMessage() {}

func (x *TextsAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_srv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextsAnswer.ProtoReflect.Descriptor instead.
func (*TextsAnswer) Descriptor() ([]byte, []int) {
	return file_srv_proto_rawDescGZIP(), []int{2}
}

func (x *TextsAnswer) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	T             string                 `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_srv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_srv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_srv_proto_rawDescGZIP(), []int{3}
}

func (x *Text) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Text) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

var File_srv_proto protoreflect.FileDescriptor

const file_srv_proto_rawDesc = "" +
	"\n" +
	"\tsrv.proto\x12\x04main\"\r\n" +
	"\vTextRequest\"\x1b\n" +
	"\tTextReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\vTextsAnswer\x12 \n" +
	"\x05texts\x18\x01 \x03(\v2\n" +
	".main.TextR\x05texts\"$\n" +
	"\x04Text\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01t\x18\x02 \x01(\tR\x01t2j\n" +
	"\aTextSrv\x124\n" +
	"\bGetTexts\x12\x11.main.TextRequest\x1a\x11.main.TextsAnswer\"\x000\x01\x12)\n" +
	"\bPostText\x12\n" +
	".main.Text\x1a\x0f.main.TextReply\"\x00B#Z!github.com/georgennw/flutter-grpcb\x06proto3"

var (
	file_srv_proto_rawDescOnce sync.Once
	file_srv_proto_rawDescData []byte
)

func file_srv_proto_rawDescGZIP() []byte {
	file_srv_proto_rawDescOnce.Do(func() {
		file_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_srv_proto_rawDesc), len(file_srv_proto_rawDesc)))
	})
	return file_srv_proto_rawDescData
}

var file_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_srv_proto_goTypes = []any{
	(*TextRequest)(nil), // 0: main.TextRequest
	(*TextReply)(nil),   // 1: main.TextReply
	(*TextsAnswer)(nil), // 2: main.TextsAnswer
	(*Text)(nil),        // 3: main.Text
}
var file_srv_proto_depIdxs = []int32{
	3, // 0: main.TextsAnswer.texts:type_name -> main.Text
	0, // 1: main.TextSrv.GetTexts:input_type -> main.TextRequest
	3, // 2: main.TextSrv.PostText:input_type -> main.Text
	2, // 3: main.TextSrv.GetTexts:output_type -> main.TextsAnswer
	1, // 4: main.TextSrv.PostText:output_type -> main.TextReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_srv_proto_init() }
func file_srv_proto_init() {
	if File_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_srv_proto_rawDesc), len(file_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_srv_proto_goTypes,
		DependencyIndexes: file_srv_proto_depIdxs,
		MessageInfos:      file_srv_proto_msgTypes,
	}.Build()
	File_srv_proto = out.File
	file_srv_proto_goTypes = nil
	file_srv_proto_depIdxs = nil
}
