// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: srv.proto

package flutter_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextSrv_GetTexts_FullMethodName = "/main.TextSrv/GetTexts"
	TextSrv_PostText_FullMethodName = "/main.TextSrv/PostText"
)

// TextSrvClient is the client API for TextSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextSrvClient interface {
	GetTexts(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextsAnswer], error)
	PostText(ctx context.Context, in *Text, opts ...grpc.CallOption) (*TextReply, error)
}

type textSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewTextSrvClient(cc grpc.ClientConnInterface) TextSrvClient {
	return &textSrvClient{cc}
}

func (c *textSrvClient) GetTexts(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TextsAnswer], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TextSrv_ServiceDesc.Streams[0], TextSrv_GetTexts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TextRequest, TextsAnswer]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextSrv_GetTextsClient = grpc.ServerStreamingClient[TextsAnswer]

func (c *textSrvClient) PostText(ctx context.Context, in *Text, opts ...grpc.CallOption) (*TextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextReply)
	err := c.cc.Invoke(ctx, TextSrv_PostText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextSrvServer is the server API for TextSrv service.
// All implementations must embed UnimplementedTextSrvServer
// for forward compatibility.
type TextSrvServer interface {
	GetTexts(*TextRequest, grpc.ServerStreamingServer[TextsAnswer]) error
	PostText(context.Context, *Text) (*TextReply, error)
	mustEmbedUnimplementedTextSrvServer()
}

// UnimplementedTextSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextSrvServer struct{}

func (UnimplementedTextSrvServer) GetTexts(*TextRequest, grpc.ServerStreamingServer[TextsAnswer]) error {
	return status.Error(codes.Unimplemented, "method GetTexts not implemented")
}
func (UnimplementedTextSrvServer) PostText(context.Context, *Text) (*TextReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PostText not implemented")
}
func (UnimplementedTextSrvServer) mustEmbedUnimplementedTextSrvServer() {}
func (UnimplementedTextSrvServer) testEmbeddedByValue()                 {}

// UnsafeTextSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextSrvServer will
// result in compilation errors.
type UnsafeTextSrvServer interface {
	mustEmbedUnimplementedTextSrvServer()
}

func RegisterTextSrvServer(s grpc.ServiceRegistrar, srv TextSrvServer) {
	// If the following call panics, it indicates UnimplementedTextSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextSrv_ServiceDesc, srv)
}

func _TextSrv_GetTexts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TextSrvServer).GetTexts(m, &grpc.GenericServerStream[TextRequest, TextsAnswer]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TextSrv_GetTextsServer = grpc.ServerStreamingServer[TextsAnswer]

func _TextSrv_PostText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextSrvServer).PostText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextSrv_PostText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextSrvServer).PostText(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

// TextSrv_ServiceDesc is the grpc.ServiceDesc for TextSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.TextSrv",
	HandlerType: (*TextSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostText",
			Handler:    _TextSrv_PostText_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTexts",
			Handler:       _TextSrv_GetTexts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "srv.proto",
}
